# Persistent settings with NVS-backed flash storage.

CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_NVS_DATA_CRC=y

CONFIG_SETTINGS=y
CONFIG_SETTINGS_NVS=y
CONFIG_SETTINGS_SHELL=n

CONFIG_FW_CMD_SETTINGS=y
