# Debug configuration.
#
# Keep assertions enabled, but do not enable global debug logs by default.
# Global debug logs are too noisy for interactive shell usage.

CONFIG_DEBUG=y
CONFIG_ASSERT=y

# 0 = off
# 1 = error
# 2 = warning
# 3 = info
# 4 = debug
CONFIG_LOG_DEFAULT_LEVEL=3

CONFIG_THREAD_MONITOR=y
CONFIG_INIT_STACKS=y
