# ESP32 OLED board application defaults.

CONFIG_FW_SHELL=y
CONFIG_FW_HEALTH_HEARTBEAT=n
CONFIG_FW_CMD_FW=y
CONFIG_FW_CMD_BOARD_INFO=y
CONFIG_FW_CMD_SYSTEM=y
CONFIG_FW_CMD_I2CDETECT=y

# I2C diagnostics.
CONFIG_I2C=y
CONFIG_I2C_SHELL=y
CONFIG_SHELL_GETOPT=y

# OLED display support.
CONFIG_DISPLAY=y
CONFIG_SSD1306=y
CONFIG_CHARACTER_FRAMEBUFFER=y
CONFIG_FW_DISPLAY=y
